### ISSUE TITLE
Package python code

### ISSUE THREAD

**Issue by cthoyt** [KramerChristian/NonadditivityAnalysis#1]
I just came across your package because it is heavily used in https://jcheminf.biomedcentral.com/articles/10.1186/s13321-021-00525-z. It would be great if it were packaged for reuse, I'd be willing to submit a PR with code and docs updates to show people how to use it more reproducibly

**Comment by KramerChristian** [comment]
Hi Charles,

sorry for the delayed answer. I would appreciate if you submit a PR with updates to the code and docs that improve the code. If you can prepare the code so that it can be packaged for reuse, I will also support it from my side. However, as may be evident from the time lag of my answer, I currently do not have the bandwidth to develop more code or packaging by myself.

Please let me know if your offer is still up-to-date.

Bests,
Christian

**Comment by cthoyt** [comment]
Yes, the offer is still open! I will take care of this and do my best to document the steps.
